; Dados secretos do usuario
; Modelo de arquivo de configuracao

[api-twitter]
chave_consumidor = 'SUA_CHAVE_CONSUMIDOR'
segredo_consumidor = 'SEU_SEGREDO_CONSUMIDOR'
token_acesso = 'SEU_TOKEN_ACESSO'
token_acesso_segredo = 'SEU_TOKEN_ACESSO_SEGREDO'